### ISSUE TITLE
Prepare card component of buy page as per the attached mock up

### ISSUE THREAD

**Issue by adityasharma7** [Kisan-Haat/haat-app#2]
![image](https://user-images.githubusercontent.com/15027245/66542626-c239f500-eb50-11e9-948b-0fe9a7045a1c.png)

**Comment by 200tristan** [comment]
To do remaining 
- 'cost per uom'
- 'Farmer Name Font'
- Tab alignment and reactive color
- Text Input 'Selected' highlight color
